ansible_architecture: x86_64
anaconda_home: /opt/anaconda
my_remote_tmp: /tmp
miniconda_path: '~/.miniconda'

python_version: 3
my_remote_tmp: /tmp

miniconda_environments:
 - name: dask_env
   python_version: 3.4
   pkgs: 'dask distributed s3fs pandas numpy'

miniconda_installer:
  url: 'http://repo.continuum.io/miniconda'
  file: 'Miniconda3-latest-Linux-x86_64.sh'